apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: newsfeed
  template:
    metadata:
      labels:
        app: newsfeed
    spec:
      containers:
      - name: tw-app-n
        image: docker.io/nivisco88/tw-app:version68
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8081
        env:
        - name: APP_PORT
          value: "8081"
        command: ["java -jar newsfeed.jar"]

---
apiVersion: v1
kind: Service
metadata:
  name: newsfeed
spec:
  selector:
    app: newsfeed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

---