apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
    NEWSFEED_SERVICE_TOKEN: VDEmZVdiWVhOV0cxdzFeWUdLRFB4QVdKQF5ldF4ma1g=
  # Example:
  # password: {{ .Values.password | b64enc }}