twappname              = "twapp"
location               = "East US"
service_principal_name = "twapp"
keyvault_name          = "vault"
registry_name          = "contregistry9289"
aks_cluster_name       = "twapp_aks"
node_count             = 1
username               = "linux_admin"
ssh_key_name           = "linux_ssh_key"
