name: Clojure CI

on:
  push:
    branches:
      - master

jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11.0.21'

      - name: Install Leiningen
        run: |
          wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /usr/local/bin/lein
          sudo chmod +x /usr/local/bin/lein

      - name: Install updates
        run: |
              sudo apt-get update && \
              sudo apt-get install -y \
              python3 \
              python3-pip \
              openjdk-11-jdk

      - name: Set up environment
        run: |
                echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
                echo "PATH=$PATH:$JAVA_HOME/bin" >> $GITHUB_ENV

      - name: Check versions
        run: |
              java -version && \
              python3 --version && \
              lein version

      - name: Test
        run: | 
                pwd
                make test || true

      - name: Build
        run: | 
                make libs
                make clean all

      - name: Build
        run: | 
                pwd
                ls -lrt

        
                

          

      