name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t web-app:latest .

    - name: Login to DockerHub
      run: |
        echo '$DOCKER_USERNAME'
        echo '$DOCKER_TOKEN'
        echo '$DOCKER_TOKEN' | docker login --username '$DOCKER_USERNAME' --password-stdin
          
    - name: Push docker image      
      run: docker push web-app:latest

    - name: Run Docker container
      run: docker run -p 8000:8000 web-app:latest